[[redirects]]
  from = "/*"
  to = "https://foodiesira.herokuapp.com"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
  
[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "https://foodiesira.herokuapp.com"
